from __future__ import annotations

from datetime import datetime
from typing import Protocol

from core.domain.entities.task import ScheduledTask, TaskStatus
from core.domain.entities.task_log import TaskLog


class ISchedulerRepository(Protocol):
    async def ensure_schema(self) -> None: ...
    async def save_task(self, task: ScheduledTask) -> ScheduledTask: ...
    async def get_task(self, task_id: int) -> ScheduledTask | None: ...
    async def list_tasks(self) -> list[ScheduledTask]: ...
    async def delete_task(self, task_id: int) -> None: ...
    async def get_next_due(self, as_of: datetime) -> ScheduledTask | None: ...
    async def list_due_pending(self, as_of: datetime) -> list[ScheduledTask]: ...
    async def update_status(self, task_id: int, status: TaskStatus, *, retry_count: int | None = None) -> None: ...
    async def update_enabled(self, task_id: int, enabled: bool) -> None: ...
    async def update_after_execution(
        self,
        task_id: int,
        *,
        success: bool,
        output: str | None,
        next_run: datetime | None,
        executions_remaining: int | None,
        retry_count: int = 0,
    ) -> None: ...
    async def save_log(self, log: TaskLog) -> TaskLog: ...
    async def seed_builtin(self, task: ScheduledTask) -> None: ...
    async def count_active_by_agent(self, agent_id: str) -> int: ...
