"""Generador de la referencia de configuración DESDE el schema Pydantic.

Recorre ``GlobalConfig`` + ``AgentConfig`` y produce el contenido de
``docs/config-reference.md``: la referencia canónica de TODOS los campos de
config (ruta, tipo, default, si es secreto, descripción), derivada del schema —
una sola fuente de verdad. Las descripciones salen de los docstrings de campo
(expuestos como ``FieldInfo.description`` vía ``use_attribute_docstrings``).

NO se edita el .md a mano: se regenera con ``inaki gen-docs`` y un test de drift
(``test_config_docs_drift.py``) falla si el archivo quedó desincronizado del
schema. Así el drift doc↔schema (ej. la sección de memoria obsoleta) no vuelve.

El output es DETERMINISTA (``model_fields`` preserva el orden de declaración),
requisito para que el test de drift sea estable.
"""

from __future__ import annotations

import inspect
import types
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from infrastructure.config_schema import AgentConfig, GlobalConfig

_HEADER = """# Configuration Reference (autogenerated)

> Generado desde el schema Pydantic (`infrastructure/config_schema.py`) con
> `inaki gen-docs`. **NO editar a mano** — los cambios se pierden al regenerar.
> El test `tests/unit/infrastructure/test_config_docs_drift.py` falla si este
> archivo queda desincronizado del schema.
>
> Narrativa (merge de 4 capas, flujos, ejemplos) vive en `configuracion.md`;
> acá vive solo la referencia exhaustiva de campos.
"""


def _unwrap_optional(annotation: Any) -> Any:
    """``X | None`` / ``Optional[X]`` → ``X`` (sin cambios si no es Optional)."""
    origin = get_origin(annotation)
    if origin is getattr(types, "UnionType", None) or str(origin) in (
        "typing.Union",
        "typing.Optional",
    ):
        args = [a for a in get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return args[0]
    return annotation


def _type_str(annotation: Any) -> str:
    """Anotación → string legible para la columna ``Type``."""
    # Annotated[X, ...] (ExpandedPath / RuntimePath / ExpandedPathList) → tipo
    # base X. Sin esto, el fallback ``str()`` imprime el repr del validador, que
    # incluye la DIRECCIÓN DE MEMORIA de la función → no determinista entre
    # procesos (rompería el test de drift). Se detecta por ``__metadata__``.
    if hasattr(annotation, "__metadata__"):
        return _type_str(annotation.__origin__)

    origin = get_origin(annotation)

    if origin is Literal:
        return "Literal[" + ", ".join(repr(a) for a in get_args(annotation)) + "]"

    if origin is getattr(types, "UnionType", None) or str(origin) in (
        "typing.Union",
        "typing.Optional",
    ):
        args = get_args(annotation)
        non_none = [a for a in args if a is not type(None)]
        inner = " \\| ".join(_type_str(a) for a in non_none)
        return f"{inner} \\| None" if type(None) in args else inner

    if origin in (list, set, frozenset):
        inner = ", ".join(_type_str(a) for a in get_args(annotation))
        return f"{origin.__name__}[{inner}]"

    if origin is tuple:
        inner = ", ".join(_type_str(a) for a in get_args(annotation))
        return f"tuple[{inner}]"

    if origin is dict:
        k, v = get_args(annotation)
        return f"dict[{_type_str(k)}, {_type_str(v)}]"

    if inspect.isclass(annotation):
        return annotation.__name__

    return str(annotation).replace("|", "\\|")


def _is_secret(field_info: FieldInfo) -> bool:
    extra = field_info.json_schema_extra
    return isinstance(extra, dict) and bool(extra.get("secret"))


def _default_md(field_info: FieldInfo) -> str:
    """Default del campo para la columna ``Default`` (markdown-safe)."""
    if field_info.default is not PydanticUndefined:
        if field_info.default is None:
            return "`null`"
        if isinstance(field_info.default, BaseModel):
            return "_(sub-config)_"
        return f"`{field_info.default!r}`"
    if field_info.default_factory is not None:
        return "_(default factory)_"
    return "**required**"


def _first_line(desc: str | None) -> str:
    """Primera línea de la descripción, markdown-safe (pipes escapados)."""
    if not desc:
        return ""
    linea = desc.strip().split("\n", 1)[0].strip()
    return linea.replace("|", "\\|")


def _nested_models(annotation: Any) -> list[type[BaseModel]]:
    """Modelos ``BaseModel`` dentro de la anotación: directo, Optional, list[X],
    dict[str, X]. Devuelve [] si no hay (escalares, dict genérico, etc.)."""
    unwrapped = _unwrap_optional(annotation)
    if inspect.isclass(unwrapped) and issubclass(unwrapped, BaseModel):
        return [unwrapped]
    args = get_args(unwrapped)
    out: list[type[BaseModel]] = []
    for a in args:
        if inspect.isclass(a) and issubclass(a, BaseModel):
            out.append(a)
    return out


def _emit_model(
    model: type[BaseModel],
    lines: list[str],
    documented: set[type[BaseModel]],
) -> None:
    """Emite la tabla de campos de ``model`` y recursa en sub-modelos no vistos."""
    lines.append("| Field | Type | Default | Secret | Description |")
    lines.append("|---|---|---|---|---|")
    nested: list[type[BaseModel]] = []
    for name, field_info in model.model_fields.items():
        annotation = field_info.annotation
        secret = "🔒" if _is_secret(field_info) else ""
        lines.append(
            f"| `{name}` | `{_type_str(annotation)}` | {_default_md(field_info)} "
            f"| {secret} | {_first_line(field_info.description)} |"
        )
        for sub in _nested_models(annotation):
            if sub not in documented and sub not in nested:
                nested.append(sub)
    lines.append("")
    for sub in nested:
        if sub in documented:
            continue
        documented.add(sub)
        lines.append(f"### `{sub.__name__}`")
        lines.append("")
        _emit_model(sub, lines, documented)


def generate_config_reference() -> str:
    """Genera el contenido completo de ``docs/config-reference.md`` desde el schema."""
    lines: list[str] = [_HEADER]
    documented: set[type[BaseModel]] = set()
    for root, titulo in (
        (GlobalConfig, "GlobalConfig — `config/global.yaml`"),
        (AgentConfig, "AgentConfig — `config/agents/{id}.yaml`"),
    ):
        lines.append(f"## {titulo}")
        lines.append("")
        _emit_model(root, lines, documented)
    return "\n".join(lines).rstrip() + "\n"
