"""Generador de la referencia de configuración DESDE el schema Pydantic.

Recorre ``GlobalConfig`` + ``AgentConfig`` y produce el contenido de
``docs/config-reference.md``: la referencia canónica de TODOS los campos de
config (ruta, tipo, default, si es secreto, descripción), derivada del schema —
una sola fuente de verdad. Las descripciones salen de los docstrings de campo
(expuestos como ``FieldInfo.description`` vía ``use_attribute_docstrings``).

NO se edita el .md a mano: se regenera con ``inaki gen-docs`` y un test de drift
(``test_config_docs_drift.py``) falla si el archivo quedó desincronizado del
schema. Así el drift doc↔schema (ej. la sección de memoria obsoleta) no vuelve.

El output es DETERMINISTA (``model_fields`` preserva el orden de declaración),
requisito para que el test de drift sea estable.
"""

from __future__ import annotations

import inspect
import types
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from infrastructure.config_schema import CHANNEL_SCHEMAS, AgentConfig, GlobalConfig

_HEADER = """# Configuration Reference (autogenerated)

> Generado desde el schema Pydantic (`infrastructure/config_schema.py`) con
> `inaki gen-docs`. **NO editar a mano** — los cambios se pierden al regenerar.
> El test `tests/unit/infrastructure/test_config_docs_drift.py` falla si este
> archivo queda desincronizado del schema.
>
> Narrativa (merge de capas, flujos, ejemplos) vive en `configuracion.md`;
> acá vive solo la referencia exhaustiva de campos.
"""


def _unwrap_optional(annotation: Any) -> Any:
    """``X | None`` / ``Optional[X]`` → ``X`` (sin cambios si no es Optional)."""
    origin = get_origin(annotation)
    if origin is getattr(types, "UnionType", None) or str(origin) in (
        "typing.Union",
        "typing.Optional",
    ):
        args = [a for a in get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return args[0]
    return annotation


def _type_str(annotation: Any) -> str:
    """Anotación → string legible para la columna ``Type``."""
    # Annotated[X, ...] (ExpandedPath / RuntimePath / ExpandedPathList) → tipo
    # base X. Sin esto, el fallback ``str()`` imprime el repr del validador, que
    # incluye la DIRECCIÓN DE MEMORIA de la función → no determinista entre
    # procesos (rompería el test de drift). Se detecta por ``__metadata__``.
    if hasattr(annotation, "__metadata__"):
        return _type_str(annotation.__origin__)

    origin = get_origin(annotation)

    if origin is Literal:
        return "Literal[" + ", ".join(repr(a) for a in get_args(annotation)) + "]"

    if origin is getattr(types, "UnionType", None) or str(origin) in (
        "typing.Union",
        "typing.Optional",
    ):
        args = get_args(annotation)
        non_none = [a for a in args if a is not type(None)]
        inner = " \\| ".join(_type_str(a) for a in non_none)
        return f"{inner} \\| None" if type(None) in args else inner

    if origin in (list, set, frozenset):
        inner = ", ".join(_type_str(a) for a in get_args(annotation))
        return f"{origin.__name__}[{inner}]"

    if origin is tuple:
        inner = ", ".join(_type_str(a) for a in get_args(annotation))
        return f"tuple[{inner}]"

    if origin is dict:
        k, v = get_args(annotation)
        return f"dict[{_type_str(k)}, {_type_str(v)}]"

    if inspect.isclass(annotation):
        return annotation.__name__

    return str(annotation).replace("|", "\\|")


def _is_secret(field_info: FieldInfo) -> bool:
    extra = field_info.json_schema_extra
    return isinstance(extra, dict) and bool(extra.get("secret"))


def _default_md(field_info: FieldInfo) -> str:
    """Default del campo para la columna ``Default`` (markdown-safe)."""
    if field_info.default is not PydanticUndefined:
        if field_info.default is None:
            return "`null`"
        if isinstance(field_info.default, BaseModel):
            return "_(sub-config)_"
        return f"`{field_info.default!r}`"
    if field_info.default_factory is not None:
        return "_(default factory)_"
    return "**required**"


def _primer_parrafo(desc: str | None) -> str:
    """Primer párrafo de la descripción, unido en una sola línea.

    No sirve tomar la primera línea FÍSICA: los docstrings del schema envuelven
    a ~88 columnas, así que eso cortaba la frase a la mitad ("Espera mínima
    (segundos) ANTES de cada llamada al provider dentro del"). El párrafo es la
    unidad semántica; el envoltorio es un accidente del formateo.
    """
    if not desc:
        return ""
    lineas: list[str] = []
    for linea in desc.strip().split("\n"):
        if not linea.strip():
            break
        lineas.append(linea.strip())
    return " ".join(lineas)


def _first_line(desc: str | None) -> str:
    """Primer párrafo, markdown-safe (pipes escapados) para una fila de tabla."""
    return _primer_parrafo(desc).replace("|", "\\|")


def _nested_models(annotation: Any) -> list[type[BaseModel]]:
    """Modelos ``BaseModel`` dentro de la anotación: directo, Optional, list[X],
    dict[str, X]. Devuelve [] si no hay (escalares, dict genérico, etc.)."""
    unwrapped = _unwrap_optional(annotation)
    if inspect.isclass(unwrapped) and issubclass(unwrapped, BaseModel):
        return [unwrapped]
    args = get_args(unwrapped)
    out: list[type[BaseModel]] = []
    for a in args:
        if inspect.isclass(a) and issubclass(a, BaseModel):
            out.append(a)
    return out


def _emit_model(
    model: type[BaseModel],
    lines: list[str],
    documented: set[type[BaseModel]],
) -> None:
    """Emite la tabla de campos de ``model`` y recursa en sub-modelos no vistos."""
    lines.append("| Field | Type | Default | Secret | Description |")
    lines.append("|---|---|---|---|---|")
    nested: list[type[BaseModel]] = []
    for name, field_info in model.model_fields.items():
        annotation = field_info.annotation
        secret = "🔒" if _is_secret(field_info) else ""
        lines.append(
            f"| `{name}` | `{_type_str(annotation)}` | {_default_md(field_info)} "
            f"| {secret} | {_first_line(field_info.description)} |"
        )
        for sub in _nested_models(annotation):
            if sub not in documented and sub not in nested:
                nested.append(sub)
    lines.append("")
    for sub in nested:
        if sub in documented:
            continue
        documented.add(sub)
        lines.append(f"### `{sub.__name__}`")
        lines.append("")
        _emit_model(sub, lines, documented)


def generate_config_reference() -> str:
    """Genera el contenido completo de ``docs/config-reference.md`` desde el schema."""
    lines: list[str] = [_HEADER]
    documented: set[type[BaseModel]] = set()
    for root, titulo in (
        (GlobalConfig, "GlobalConfig — `config/global.yaml`"),
        (AgentConfig, "AgentConfig — `agents/{id}.yaml`"),
    ):
        lines.append(f"## {titulo}")
        lines.append("")
        _emit_model(root, lines, documented)

    # Los canales entran como raíces propias: ``AgentConfig.channels`` es un dict
    # indexado por nombre de canal, así que la recursión por anotaciones no puede
    # descubrirlos. Sin esto, los 26 campos de Telegram/Broadcast quedaban fuera
    # de una referencia que se anuncia como exhaustiva.
    lines.append("## Channels — `agents/{id}.yaml` → `channels.<nombre>`")
    lines.append("")
    for nombre, modelo in sorted(CHANNEL_SCHEMAS.items()):
        lines.append(f"### `channels.{nombre}`")
        lines.append("")
        documented.add(modelo)
        _emit_model(modelo, lines, documented)
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# global.example.yaml — referencia comentada, generada desde el mismo schema
# ---------------------------------------------------------------------------

_EJEMPLO_HEADER = """\
# =============================================================================
# Inaki — Configuración Global de Referencia
# =============================================================================
#
# GENERADO desde el schema Pydantic (`infrastructure/config_schema.py`) con
# `inaki gen-docs`. NO editar a mano: los cambios se pierden al regenerar, y el
# test `test_config_docs_drift.py` falla si queda desincronizado.
#
# Para documentar un parámetro, escribí su docstring en el schema: de ahí salen
# los comentarios de este fichero, la columna Description de
# `docs/config-reference.md` y la ayuda del setup TUI.
#
# Este fichero NO se lee en runtime — es la referencia canónica de qué se puede
# configurar. La config real vive en:
#
#   ~/.inaki/config/global.yaml   ← capa base
#   ~/.inaki/agents/{id}.yaml     ← completa o pisa lo que declara
#
# Credenciales: viven en esas MISMAS dos capas (`providers.*.api_key`, tokens de
# canal, `admin.auth_key`). No hay ficheros `*.secrets.yaml`. Ambas capas se
# crean con permisos 600 y NUNCA se commitean; el único fichero compartible es
# este ejemplo, que no lleva valores reales.
# =============================================================================
"""


_ANCHO_COMENTARIO_INLINE = 60
"""Umbral para pasar la descripción de comentario inline a línea propia."""

_ANCHO_YAML = 88
"""Ancho de línea del YAML generado (mismo que usa ruff en el repo)."""


def _envolver(texto: str, indent: str = "") -> str:
    """Envuelve un párrafo al ancho del fichero, descontando indent y ``# ``."""
    import textwrap

    disponible = max(_ANCHO_YAML - len(indent) - 2, 40)
    return "\n".join(textwrap.wrap(texto, width=disponible))


def _comentar(texto: str, indent: str = "") -> list[str]:
    """Convierte un docstring en líneas de comentario YAML.

    Preserva la indentación RELATIVA: los docstrings del schema usan listas y
    bloques indentados, y aplanarlos los volvía ilegibles.
    """
    salida = []
    for linea in texto.split("\n"):
        cuerpo = linea.rstrip()
        salida.append(f"{indent}# {cuerpo}" if cuerpo else f"{indent}#")
    return salida


def _docstring_de_clase(modelo: type[BaseModel]) -> str:
    return inspect.cleandoc(modelo.__doc__ or "").strip()


def _modelo_de_campo(field_info: FieldInfo) -> type[BaseModel] | None:
    """Sub-modelo de un campo, desenvolviendo ``Optional``."""
    candidatos = _nested_models(field_info.annotation)
    return candidatos[0] if candidatos else None


def _volcar_valor(valor: Any) -> str:
    """Serializa un default a YAML inline, en una línea."""
    import yaml as _yaml

    volcado = _yaml.safe_dump(valor, default_flow_style=True, allow_unicode=True).strip()
    return volcado.removesuffix("...").strip()


def _emitir_bloque(modelo: type[BaseModel], lines: list[str], nivel: int) -> None:
    """Emite los campos de ``modelo`` como YAML comentado, recursando en sub-bloques."""
    indent = "  " * nivel
    for nombre, field_info in modelo.model_fields.items():
        descripcion = _primer_parrafo(field_info.description)
        submodelo = _modelo_de_campo(field_info)

        # Lista de modelos (``knowledge.sources``): se emite VACÍA con la forma
        # de un elemento comentada debajo. Volcarla como bloque anidado producía
        # un YAML que el propio schema rechaza ("Input should be a valid list").
        if submodelo is not None and _es_tipo_lista(field_info.annotation):
            if descripcion:
                lines.extend(_comentar(_envolver(descripcion, indent), indent))
            lines.append(f"{indent}{nombre}: []")
            forma: list[str] = []
            _emitir_bloque(submodelo, forma, 0)
            lines.append(f"{indent}#   - forma de cada elemento:")
            lines.extend(f"{indent}#       {linea}" for linea in forma if linea.strip())
            continue

        if submodelo is not None and not _es_tipo_dict(field_info.annotation):
            if descripcion:
                lines.extend(_comentar(_envolver(descripcion, indent), indent))
            lines.append(f"{indent}{nombre}:")
            _emitir_bloque(submodelo, lines, nivel + 1)
            continue

        default = field_info.get_default(call_default_factory=True)
        if default is PydanticUndefined:
            default = None
        if isinstance(default, BaseModel):
            default = default.model_dump()
        # Descripción corta → comentario inline; larga → arriba del campo, para
        # que no se corte contra el margen ni empuje el valor fuera de vista.
        if descripcion and len(descripcion) > _ANCHO_COMENTARIO_INLINE:
            lines.extend(_comentar(_envolver(descripcion, indent), indent))
            lines.append(f"{indent}{nombre}: {_volcar_valor(default)}")
        else:
            sufijo = f"   # {descripcion}" if descripcion else ""
            lines.append(f"{indent}{nombre}: {_volcar_valor(default)}{sufijo}")


def _es_tipo_dict(annotation: Any) -> bool:
    return get_origin(_unwrap_optional(annotation)) is dict


def _es_tipo_lista(annotation: Any) -> bool:
    return get_origin(_unwrap_optional(annotation)) is list


def generate_global_example() -> str:
    """Genera ``config/global.example.yaml`` desde el schema.

    Cada bloque top-level lleva como cabecera el docstring de SU CLASE, y cada
    campo su valor por defecto con la primera línea de su docstring. Antes este
    fichero se mantenía a mano y se desincronizaba: al momento de automatizarlo
    le faltaban cinco bloques enteros del schema (`scheduler`, `transcription`,
    `delegation`, `photos`, `knowledge`).
    """
    lines: list[str] = [_EJEMPLO_HEADER]

    for nombre, field_info in GlobalConfig.model_fields.items():
        submodelo = _modelo_de_campo(field_info)
        lines.append("")
        lines.append("# " + "-" * 77)
        lines.append(f"# [{nombre}]")
        lines.append("# " + "-" * 77)

        doc_clase = _docstring_de_clase(submodelo) if submodelo is not None else ""
        if doc_clase:
            lines.append("#")
            lines.extend(_comentar(doc_clase))
        if (
            field_info.get_default(call_default_factory=True) is None
            and not field_info.is_required()
        ):
            lines.append("#")
            lines.append("# Bloque OPCIONAL: si se omite, la feature queda desactivada.")
        lines.append("")

        if submodelo is None or _es_tipo_dict(field_info.annotation):
            # `providers` y `channels` son dicts indexados por el operador: no
            # tienen campos fijos que volcar, se muestran con un ejemplo.
            lines.append(f"{nombre}:")
            if submodelo is not None:
                lines.append("  # <clave elegida por vos>:")
                sub: list[str] = []
                _emitir_bloque(submodelo, sub, 2)
                lines.extend(f"  # {linea.strip()}" for linea in sub if linea.strip())
            continue

        lines.append(f"{nombre}:")
        _emitir_bloque(submodelo, lines, 1)

    return "\n".join(lines).rstrip() + "\n"
